// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHMBT0U6AaLQMdwgrJ_xt6MNoZNOPCq8',
    appId: '1:514292837708:web:78cecf5f4a74d96547f3e9',
    messagingSenderId: '514292837708',
    projectId: 'food-deliver-app-7ecee',
    authDomain: 'food-deliver-app-7ecee.firebaseapp.com',
    storageBucket: 'food-deliver-app-7ecee.appspot.com',
    measurementId: 'G-VRHV9Z97BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSq93vhmSUYwcSGMU9THor4s-zgtwegk',
    appId: '1:514292837708:android:5a376520c8baa7fb47f3e9',
    messagingSenderId: '514292837708',
    projectId: 'food-deliver-app-7ecee',
    storageBucket: 'food-deliver-app-7ecee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKSLHUZaJrsbvkWbcnWTg3xMgmCZPnac',
    appId: '1:514292837708:ios:b455c62f90a98b3747f3e9',
    messagingSenderId: '514292837708',
    projectId: 'food-deliver-app-7ecee',
    storageBucket: 'food-deliver-app-7ecee.appspot.com',
    iosBundleId: 'com.example.foodDeliverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQKSLHUZaJrsbvkWbcnWTg3xMgmCZPnac',
    appId: '1:514292837708:ios:bc0a589e404361f847f3e9',
    messagingSenderId: '514292837708',
    projectId: 'food-deliver-app-7ecee',
    storageBucket: 'food-deliver-app-7ecee.appspot.com',
    iosBundleId: 'com.example.foodDeliverApp.RunnerTests',
  );
}
